org: rafaelram
service: api-s3

provider:
  name: aws
  runtime: python3.13
  # Default memory size for functions (default: 256MB)
  memorySize: 256
  timeout: 30
  iam:
    role: arn:aws:iam::969784661290:role/LabRole

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda

###### TAREA
  crear_directorio:
    handler: crear_directorio.lambda_handler
    events:
      - http:
          path: /s3/folder
          method: post
          cors: true

  subir_archivo_base64:
    handler: subir_base64.lambda_handler
    events:
      - http:
          path: /s3/upload
          method: post
          cors: true


resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-s3rrh-bucket-${sls:stage}-${aws:accountId}
